### ISSUE TITLE
update map

### ISSUE THREAD

**Issue by sgassler** [wimagguc/jquery-latitude-longitude-picker-gmaps#12]
not really an issue, just a question.. and I'm new to Github so I wast sure where to post this (sorry).

How can I call the "update map" functionality? I have a custom script and I need to call this function at the end of my script to update the map view after a user selects a city from a drop down menu which will auto fill GPS coordinates from my DB.

Thanks!

**Comment by sgassler** [comment]
Found a work around, but I am not sure if this would be the best way.

add an id to the button, in my case "auto_click"

and then add the following code to the end of the custom JavaScript function:
`document.getElementById('auto_click').click();`

**Comment by wimagguc** [comment]
It's probably a quick-and-easy workaround actually, but for a clean solution you can also check out the "gllp_perform_search" and "gllp_update_fields" listeners. (For example, just update the .gllpLatitude and .gllpLongitude input fields first, then trigger the event and wait for the map to update.)
